Fix
nekromant322/SSHKeyKeeper pull request #12
Opened 2024-08-09 15:25 UTC by l2ilai

много всего по мелочи + избавился от файла скрипта, всё перенёс в баш команду. Создал дефолтного админ-пользователя в коде.  Удалил роли и пароли пользователей, исправил проверку юзера на содержание сервера, заменил приходящий от пользователя документ и приписку к нему на потокобезопасную хеш-мапу

2024-08-09 22:36 UTC, nekromant322 commented on src/main/java/com/override/telegram_bot/Bot.java
> +//    private String caption;
а зачем оставлять это в коде?

2024-08-09 22:38 UTC, nekromant322 commented on src/main/java/com/override/telegram_bot/config/SecurityConfig.java
> +                .password("$2y$10$O0vKt3oXzrPvU6bup5VBoe6.1rzEtu6nr5DEsQ7nXNNsPLfGcLH86")
думаю стоит положить это в сикреты, причем не ввиде хеша, чтоб потом если забыл - можно было сменить быстро и удобно  
а тут просто оставить bcrypt.encode(<пароль из сикрета>)

2024-08-09 22:38 UTC, nekromant322 requested changes
создать енв для пароля и поехали

2024-08-10 12:10 UTC, l2ilai commented
ок

2024-08-10 12:10 UTC, l2ilai commented on src/main/java/com/override/telegram_bot/Bot.java
> +//    private String caption;
забыл(

2024-08-10 20:24 UTC, nekromant322 commented on src/main/resources/application.yaml
> +  pass: ${WEB_PASS}
подумой о тех кто будет потом локально запускать  
проставь дефолтное значение)

2024-08-10 20:24 UTC, nekromant322 commented on src/main/resources/application.yaml
> +  pass: ${WEB_PASS}
разве через композ не надо этот енв прокинуть? как он в контейнер из сикретов всосется?  
ну и в пайплайн до кучи

2024-08-14 19:20 UTC, nekromant322 approved these changes

2024-08-14 21:35 UTC, merged